Repository viveakrt/Competitive-programing, pull requests merged in 2020-10, with the labels that each got.

#6 Added a Codechef problem sol
  CodeChef/CHEFWARS.py
Labels: documentation, good first issue, hacktoberfest-accepted

#7 Added Chef and Secret Password
  CodeChef/Chef_and_Secret_Password_(SECPASS).py
Labels: documentation, good first issue, hacktoberfest-accepted

#8 Added codeforces 1408D
  Codeforces/1408D Searchlights.cpp
Labels: documentation, good first issue, hacktoberfest-accepted

#11 Add BOWLERS solution to Codechef in Java
  CodeChef/Bowlers.java
Labels: Explanation, good first issue, hacktoberfest-accepted

#10 Added Codechef Solutions
  CodeChef/LRPRINT_Left_Right_Print.c
  CodeChef/MAGICHF_MagicianVersusChef.c
  CodeChef/MAGICJAR_Chef_And_Magical_Jars.c
  CodeChef/MAKPERM_MakeAPermutation.c
  CodeChef/MATBREAK_MatrixDecomposition.c
  CodeChef/MATCHES_Playing_With_Matches.c
  CodeChef/MAXEP_MaxAndElectricalPanel.c
  CodeChef/MAXREM_Maximum_Remaining.c
  CodeChef/MGAME_Chef_And_Modulo_Game.c
  CodeChef/MMAX_MinimumAndMaximum.c
Labels: Explanation Required, Great Job, hacktoberfest-accepted

#13 Added Codechef sol
  CodeChef/PriyaandAND.py
Labels: Explanation Required, Great Job, hacktoberfest-accepted

#14 solutions to 800 rated problems on codeforces. merge my pr
  Codeforces/467A_George_and_Accomodation.cpp
  Codeforces/469A_I_Wanna_Be_the_Guy.cpp
  Codeforces/472A_Design_Tutorial_Learn_from_Math.cpp
  Codeforces/486A_Calculating_Function.cpp
  Codeforces/510A_Fox_and_Snake.cpp
  Codeforces/520A_Pangram.cpp
  Codeforces/546A_Soldier_and_Bananas.cpp
  Codeforces/581A_Vasya_the_Hipster.cpp
  Codeforces/617A_Elephant.cpp
Labels: Add Question URL, Explanation Required, Great Job, good first issue, hacktoberfest-accepted

#15 Create UNITGCD.py
  CodeChef/UNITGCD Unit GCD.py
Labels: Explanation Required, Great Job, good first issue, hacktoberfest-accepted

#16 Revert "solutions to 800 rated problems on codeforces. merge my pr"
  Codeforces/467A_George_and_Accomodation.cpp
  Codeforces/469A_I_Wanna_Be_the_Guy.cpp
  Codeforces/472A_Design_Tutorial_Learn_from_Math.cpp
  Codeforces/486A_Calculating_Function.cpp
  Codeforces/510A_Fox_and_Snake.cpp
  Codeforces/520A_Pangram.cpp
  Codeforces/546A_Soldier_and_Bananas.cpp
  Codeforces/581A_Vasya_the_Hipster.cpp
  Codeforces/617A_Elephant.cpp
Labels: Add Question URL, Great Job, good first issue

#17 Create ADAKING_Ada King.py
  CodeChef/AdaKing.py
Labels: Explanation Required, Great Job

#20 Add CF282-D2-E solution to CF library.
  Codeforces/CF282-D2-E.txt
Labels: Add Question URL, Great Job

#21 Create EOEO_The Tom and Jerry Game!.py
  CodeChef/EOEO_The Tom and Jerry Game!.py
Labels: Great Job

#22 EVENM_Even_Matrix.py
  CodeChef/EVENM.py
Labels: Explanation Required, Great Job, good first issue

#25 PTMSSNG_Missing_a_Point.py
  CodeChef/PTMSSNG_Missing_a_Point.py
Labels: Great Job, good first issue

#27 Add solution to Monk_and_Rotation.cpp
  Hackerearth_codemonk/Basic Input Output/Monk_and_Rotation.cpp
Labels: Add Question URL, Explanation Required, good first issue

#29 Create WICP006_Sign_Wave.py
  CodeChef/WICP006_Sign_Wave.py
Labels: Great Job, good first issue

#28 CRDGAME_Chef_and_Card_Game.py
  CodeChef/CRDGAME_Chef_and_Card_Game.py
Labels: Great Job

#32 add problem Replace for X
  CodeChef/REPLESX_Replace_For_X.cpp
Labels: Explanation Required, Great Job, good first issue, hacktoberfest-accepted

#31 Create CACHEHIT_Cache_hit.py
  CodeChef/CACHEHIT_Cache_hit.py
  Codeforces/1370A_Maximum_GCD.cpp
Labels: Great Job, good first issue

#34 2 CF problems added
  CodeChef/SUBREM_subrem.cpp
  Codeforces/204B_jeff_and_periods.cpp
  Codeforces/254A_dzy_loves_chessboard.cpp
Labels: Great Job, good first issue

#35 IARCS OPC JUDGE PROBLEMS
  CodeChef/Average.cpp
  CodeChef/Discrepancies_in_the_Voters_List.cpp
  CodeChef/Dividing_Squences.cpp
  CodeChef/End_of_Corruption.cpp
  CodeChef/Find_the_Permutation.cpp
  CodeChef/Lead_Game.cpp
  CodeChef/List_of_Books.cpp
  CodeChef/Longest_Palindrome.cpp
  CodeChef/Next_Permutation.cpp
  CodeChef/Permutation_Cycles.cpp
  CodeChef/Reverse.cpp
  CodeChef/Whats_the_Rank.cpp
  CodeChef/Word_list.cpp
  CodeChef/Zero_One_Tiles.cpp
Labels: Waiting for edit, good first issue

#42 Added Unit GCD code from CodeChef.
  CodeChef/UNITGCD_Unit_GCD.c
Labels: Explanation Required, Great Job, good first issue

#43 Add Remove One Element Codeforces in C++
  Codeforces/1272D_Remove_One_Element.cpp
Labels: Great Job

#44 Create 1256A_Payment_Without_Change.py
  Codeforces/1256A_Payment_Without_Change
  Codeforces/1324A_Yet_Another_Tetris_Problem.py
Labels: Great Job, good first issue

#50 Add files via upload
  Google/round1A2020_pattern_matching.cpp
Labels: Add Question URL, good first issue, hacktoberfest-accepted

#64 Add HELPLIRA_Helping_Lira solution
  CodeChef/HELPLIRA_Helping_Lira.cpp
Labels: good first issue
