Repository viveakrt/Competitive-programing, pull requests merged in 2020-11, with the labels that each got.

#54 Create Perform Easily
  Codeforces/Perform Easily
Labels: Add Question URL, Explanation Required, Rename File

#55 Create Two Platforms
  Codeforces/Two Platforms
Labels: Add Question URL, Rename File

#56 Create Putting bricks in the wall
  Codeforces/Putting bricks in the wall
Labels: Add Question URL, Rename File

#57 Create Hexagons
  Codeforces/Hexagons
Labels: Add Question URL, Rename File, Waiting for edit

#70 Create KMP Algorithm
  CodeChef/KMP Algorithm
Labels: Add Question URL, Rename File, Waiting for edit
