Repository viveakrt/Competitive-programing, pull requests merged in 2021-10, with the labels that each got.

#89 Update MNDIGSUM_MinimizeDigitSum.cpp
  CodeChef/MNDIGSUM_MinimizeDigitSum.c
Labels: hacktoberfest-accepted

#90 🚗 1154A Restoring the number
  Codeforces/1154A Restoring Three Number.py
Labels: hacktoberfest-accepted

#108 Added hacker rank solution
  HackerRank/3D_surface_Area.c
  HackerRank/Encryption.c
  HackerRank/Forming_a_magic_square.c
  HackerRank/The_Time_In_Words.c
Labels: hacktoberfest-accepted, Great Job

#95 solution of productive meeting
  Codeforces/1579D_Productive_Meeting.cpp
Labels: hacktoberfest-accepted

#98 :sparkles: CodeWars solutions
  CodeWars/Bit Counting.py
  CodeWars/Build Tower.py
  CodeWars/Calculating with Functions.py
  CodeWars/Categorize New Member.py
  CodeWars/Complementary DNA.py
  CodeWars/Convert string to camel case.py
  CodeWars/Create Phone Number.py
  CodeWars/Delete occurrences of an element if it occurs more than n times.py
  CodeWars/Delete occurrences of an element if it occurs more.py
  CodeWars/Dubstep.py
  CodeWars/Duplicate Encoder.py
  CodeWars/Find Product.py
  CodeWars/Find The Parity Outlier.py
  CodeWars/Find the next perfect square.py
  CodeWars/Format a string of names like 'Bart, Lisa & Maggie'.py
  CodeWars/Growth of a Population.py
  CodeWars/Isograms.py
  CodeWars/Molecule to atoms.py
  CodeWars/Persistent Bugger.py
  CodeWars/Pete, the baker.py
  CodeWars/Pick peaks.py
  CodeWars/Regex validate PIN code.py
  CodeWars/Shortest Word.py
  CodeWars/Simple Pig Latin.py
  CodeWars/Sort the odd.py
  CodeWars/Sudoku Solution Validator.py
  CodeWars/Take a Number And Sum Its Digits Raised To The Consecutive Powers And Eureka.py
  CodeWars/Unique In Order.py
  CodeWars/Weight for weight.py
  CodeWars/Who likes it.py
  CodeWars/Your order, please.py
Labels: hacktoberfest-accepted

#100 add Casimir's String Solitaire solution
  Codeforces/1579A_Casimir's_String_Solitaire.cpp
Labels: hacktoberfest-accepted

#101 add Towers solution
  Codeforces/37A_Towers.cpp
Labels: hacktoberfest-accepted

#102 add Countdown solution
  Codeforces/1573A_Countdown.cpp
Labels: hacktoberfest-accepted

#110 Add New Solution in Google Folder of CodeJam Qualification 2021 Problem Reversort
  Google/Code Jam Qualification Round Revesort.cpp
Labels: hacktoberfest-accepted

#103 added codeforces solution
  Codeforces/1555C_Coin_Rows.cpp
  Codeforces/1569B_Chess_Tournament.cpp
Labels: hacktoberfest-accepted

#104 add Polygon solution
  Codeforces/1360E_Polygon.cpp
Labels: hacktoberfest-accepted

#106 Add New Solution in Codeforces Folder of CF Round 715 (Div2) Problem B
  Codeforces/CF 1509B.cpp
Labels: hacktoberfest-accepted

#105 Add New Solution in Google Folder of KickStart_Round D 2021_Arithmetic Square
  Google/KickStart_Round D 2021_Arithmetic Square.cpp
Labels: hacktoberfest-accepted, Great Job

#113 add Initial Bet
  Codeforces/478A_Initial_Bet.cpp
Labels: hacktoberfest-accepted

#117 add problem Amusing_Joke in cpp
  Codeforces/141A_Amusing_Joke.cpp
Labels: hacktoberfest-accepted, Great Job

#119 add problem Review_site
  Codeforces/1511A_Review_Site.cpp
Labels: hacktoberfest-accepted

#124 Adding Solution of Codeforces Round 744 Problem-B solution
  Codeforces/1579B_Shifting_Sort.cpp
Labels: hacktoberfest-accepted, Great Job

#123 HackerRank Solution Added
  HackerRank/Utopian_Tree.c
Labels: hacktoberfest-accepted

#135 Added Sherlocks and square python prg under hackerank folder
  HackerRank/sherlocks_and_squares.py
Labels: hacktoberfest-accepted

#133 Hackerrank: add encryption using Go
  HackerRank/Encryption.go
  HackerRank/new.py
Labels: hacktoberfest-accepted

#139 Hackerrank: add recursive digit sum using Go
  .vscode/launch.json
  HackerRank/recursive_digit_sum.go
Labels: hacktoberfest-accepted

#138 Add Hackerrank solution
  HackerRank/ArrayManipulation.java
Labels: hacktoberfest-accepted

#132 Added solution to 750- A New Year and Hurry
  Codeforces/750A_New_Year_and_Hurry.cpp
Labels: hacktoberfest-accepted

#96 Added 501_C_Songs_Compression code
  Codeforces/501_C_Songs_Compression.cpp
Labels: Add Question URL

#125 added solutions to SPOJ problems
  SPOJ/acquire.cpp
  SPOJ/adaaphid.cpp
  SPOJ/adacrop.cpp
  SPOJ/adaindex.cpp
  SPOJ/allin1.cpp
  SPOJ/altseq.cpp
  SPOJ/bsheep.cpp
  SPOJ/cot.cpp
  SPOJ/count1it.cpp
  SPOJ/dquery.cpp
  SPOJ/dynacon1.cpp
  SPOJ/flib.cpp
  SPOJ/giveaway.cpp
  SPOJ/gss1.cpp
  SPOJ/hmlis.cpp
  SPOJ/kaos.cpp
  SPOJ/koiline.cpp
  SPOJ/kquery.cpp
  SPOJ/larmy.cpp
  SPOJ/matsum.cpp
  SPOJ/max_num.cpp
  SPOJ/mkthnum.cpp
  SPOJ/orderset.cpp
  SPOJ/phonelst.cpp
  SPOJ/policemen.cpp
  SPOJ/psegtree.cpp
  SPOJ/qtree.cpp
  SPOJ/qtree2.cpp
  SPOJ/qtree3.cpp
  SPOJ/qtree5.cpp
  SPOJ/salman.cpp
  SPOJ/treap.cpp
  SPOJ/trycomp.cpp
  SPOJ/ttm.cpp
  SPOJ/twist.cpp
  SPOJ/xorx.cpp
Labels: Add Question URL

#122 Added 1530-D Secret Santa Code
  Codeforces/1530_D_Secret_Santa.cpp
Labels: hacktoberfest-accepted

#130 Sarthak815 patch 1
  HackerRank/Halloween_Sale.cpp
  HackerRank/Happy_Ladybugs.cpp
Labels: hacktoberfest-accepted

#114 Simple Multiplication py one liner
  CodeWars/Simple Multiplication.py
Labels: hacktoberfest-accepted, Great Job

#151 Hackerrank: add sherlocks and squares solution using Go
  HackerRank/sherlocks_and_squares.go
Labels: hacktoberfest-accepted

#145 separate the number (added question url)
  HackerRank/separateno.cpp
Labels: hacktoberfest-accepted

#112 Chefora_Codechef_JulyLong21_Div2
  CodeChef/CHEFORA_JulyLong.cpp
Labels: hacktoberfest-accepted

#149 Codeforces 49A Sleuth
  Codeforces/1467A_Wizard_of_Orz.cpp
  Codeforces/49A Sleuth.cpp
Labels: hacktoberfest-accepted

#150 adding more questions
  Codeforces/554A - Kyoya and Photobooks.py
  Codeforces/567A - Lineland Mail.py
  Codeforces/588A - Duff and Meat.py
  Codeforces/588B - Duff in Love.py
  Codeforces/58A - Chat room.py
  Codeforces/611A - New Year and Days.py
  Codeforces/611B - New Year and Old Property.py
Labels: hacktoberfest-accepted

#146 CodeChef Magical Door Problem Added
  CodeChef/MAGDOORS_Magical_Doors.cpp
Labels: hacktoberfest-accepted

#148 Added 1552C Maximize the Intersections
  Codeforces/1552C_Maximize_the_Intersections.cpp
Labels: hacktoberfest-accepted

#147 Magical Door Problem Added
  CodeChef/DIWALI1_Maximum Light Up.cpp
Labels: hacktoberfest-accepted

#158 1399A
  Codeforces/1399A Remove Smallest.py
Labels: hacktoberfest-accepted

#155 CodeChef Chef vs Bharat Problem Added
  CodeChef/CHEFORA_Chef vs Bharat.cpp
  CodeChef/XXOORR_XxOoRr.cpp
Labels: hacktoberfest-accepted

#154 Added Codeforces problem 1385B and 1454A
  Codeforces/1385B_Restore_the_Permutation_by_Merger.cpp
  Codeforces/1454A_Special_Permutation.cpp
Labels: hacktoberfest-accepted

#152 CodeChef Grid Fill Problem Added
  CodeChef/FILLGRID_The Grid Fill Problem.cpp
Labels: hacktoberfest-accepted

#157 The hurdleRace Problem: HackerRank(Problem Url Added)
  HackerRank/HurdleRace.cpp
Labels: hacktoberfest-accepted

#162 Create BININVER_Odd GCD.cpp
  CodeChef/BININVER_Odd GCD.cpp
Labels: hacktoberfest-accepted

#159 CodeChef Marathon Problem Added
  CodeChef/Marathon_Marathon.cpp
Labels: hacktoberfest-accepted

#160 Added 1328A solution in cpp
  Codeforces/1328A_Divisibility_problem.cpp.txt
Labels: hacktoberfest-accepted

#161 Adding solution of problem A of Codeforces round 736
  Codeforces/1549A_Gregor_and_Cryptography.cpp
Labels: hacktoberfest-accepted
